### PR TITLE
Added log rotation

### PR DESCRIPTION
**Pull request by Ckarik**

### CODE REVIEW

**Comment by jordiprats** [comment]
rotate        => 7, això hauria d'anar entre cometes

també, el nom del recurs pot ser el log, pertant no cal especificar log:

 +    logrotate::logs { 'logstashLog':
+      log           => '/var/log/logstash/logstash.log',

-->

 +    logrotate::logs { '/var/log/logstash/logstash.log':

pots corretgir-ho?

**Comment by Ckarik** [comment]
Corregit

**Comment by jordiprats** [comment]
+      compress      => 'compress',
+      delaycompress => 'delaycompress',
+      notifempty    => 'notifempty',
+      frequency     => 'daily',
+      missingok     => 'missingok',

-> cal canviar a true/false

**Comment by jordiprats** [comment]
menys el frequency, clar

**Comment by Ckarik** [comment]
Nova correció pujada.

**Comment by Ckarik** [comment]
Corrected ensure present sintax error

**Pull request merged**
